version: '3.8'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: draftbash
      POSTGRES_PASSWORD: devpassword
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:devpassword@postgres:5432/draftbash?schema=public
      - JWT_SECRET=jwtsecret

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: