import { DraftSettingsDTO } from '../../../contracts/src/rest-api/shared/DraftSettingsDTO';
export declare class DraftSettings {
    private readonly orderType;
    private readonly scoringType;
    private readonly pickTimeSeconds;
    private readonly teamCount;
    private readonly pointguardSlots;
    private readonly shootingguardSlots;
    private readonly guardSlots;
    private readonly smallforwardSlots;
    private readonly powerforwardSlots;
    private readonly forwardSlots;
    private readonly centerSlots;
    private readonly utilitySlots;
    private readonly benchSlots;
    private readonly teamSize;
    constructor(settings: DraftSettingsDTO);
    getOrderType(): string;
    getScoringType(): string;
    getPickTimeSeconds(): number | null;
    getTeamCount(): number;
    getPointguardSlots(): number;
    getShootingguardSlots(): number;
    getGuardSlots(): number;
    getSmallforwardSlots(): number;
    getPowerforwardSlots(): number;
    getForwardSlots(): number;
    getCenterSlots(): number;
    getUtilitySlots(): number;
    getBenchSlots(): number;
    getTeamSize(): number;
}
